alert("Iremos somar 2 numeros!")
let numberOne = prompt("Digite o primeiro numero:")
let numberTwo = prompt("Digite o segundo numero:")
let result = Number(numberOne) + Number(numberTwo)
alert("O resultado final é: " + result)
